"""Covers the LLM-synthesis branch of app.llm.report with a fake provider,
and the exception-fallback path when the provider raises."""

from unittest.mock import patch

from app.analyzer.pipeline import run_all_analyzers
from app.graph.builder import build_graph
from app.graph.summary import compute_summary
from app.llm.report import synthesize_report
from app.parser.ecosystem import EcosystemInfo
from app.parser.extractor import parse_source


class FakeLLM:
    def __init__(self, available=True, raise_on_complete=False):
        self.is_available = available
        self._raise = raise_on_complete
        self.last_user_prompt = None

    def complete(self, system, user, max_tokens=2000):
        if self._raise:
            raise RuntimeError("provider unavailable")
        self.last_user_prompt = user
        return "# Executive Report\n\nGenerated by the fake LLM."


def _bundle():
    files = [parse_source("app.py", "python", "def add(a, b):\n    return a + b\n")]
    graph = build_graph(files)
    summary = compute_summary(files, EcosystemInfo([], []))
    analysis = run_all_analyzers(files, graph, summary)
    return summary, analysis


def test_report_uses_llm_when_available():
    summary, analysis = _bundle()
    fake = FakeLLM(available=True)

    with patch("app.llm.report.get_llm_provider", return_value=fake):
        report = synthesize_report("demo-repo", summary, analysis)

    assert report == "# Executive Report\n\nGenerated by the fake LLM."
    assert "demo-repo" in fake.last_user_prompt


def test_report_falls_back_to_template_when_llm_raises():
    summary, analysis = _bundle()
    fake = FakeLLM(available=True, raise_on_complete=True)

    with patch("app.llm.report.get_llm_provider", return_value=fake):
        report = synthesize_report("demo-repo", summary, analysis)

    assert "demo-repo" in report
    assert "LLM report generation failed" in report
    assert "Engineering Scores" in report
